version: "3.7"

services:
    # image project
    app:
        container_name: tnw-app
        build:
            context: .
            dockerfile: Dockerfile
        image: avdeisgn/tnwjeans-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - tnw-network
    
    # nginx
    nginx:
        container_name: tnw-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8000:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - tnw-network

    # db mysql
    mysql:
        container_name: tnw-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - tnw-network
    
    # db mysql
    phpmyadmin:
        container_name: tnw-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8001:80"
        networks:
            - tnw-network
        depends_on:
            - mysql       

    # queue
    queue:
        container_name: tnw-queue
        image: avdeisgn/tnwjeans-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - tnw-network

    # redis
    redis:
        container_name: tnw-redis
        image: redis:latest
        networks: 
            - tnw-network

networks: 
    tnw-network:
        driver: bridge